# Generated by Django 4.1.7 on 2023-03-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('screen_size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('hard_disk_size', models.CharField(max_length=30)),
                ('cpu_model', models.CharField(max_length=30)),
                ('ram_memory_installed_size', models.CharField(max_length=30)),
                ('operation_system', models.CharField(max_length=30)),
                ('graphics_card_description', models.CharField(max_length=30)),
                ('image_1', models.FileField(upload_to='laptops')),
                ('image_2', models.FileField(upload_to='laptops')),
                ('image_3', models.FileField(upload_to='laptops')),
                ('about', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
            ],
        ),
    ]
