# Generated by Django 4.1.7 on 2023-03-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_laptops_price'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='laptops',
            index_together={('id', 'name')},
        ),
    ]
