# Generated by Django 4.1.7 on 2023-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('joined_company', models.IntegerField()),
                ('information', models.TextField()),
                ('photo', models.FileField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('information', models.TextField()),
                ('photo', models.FileField(upload_to='img/')),
            ],
        ),
    ]
