# Generated by Django 4.1.7 on 2023-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='department',
        ),
        migrations.AlterField(
            model_name='directors',
            name='photo',
            field=models.FileField(upload_to='directors/'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.FileField(upload_to='employees/'),
        ),
    ]
