# Generated by Django 4.1.7 on 2023-03-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_employees_department_alter_directors_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('information', models.TextField()),
                ('photo', models.FileField(upload_to='senior_employees/')),
            ],
        ),
    ]
