# Generated by Django 4.1.7 on 2023-03-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_senioremployees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directors',
        ),
    ]
