# Generated by Django 4.1.7 on 2023-03-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_final', '0002_category_conference_alter_news_options_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='category',
            field=models.ManyToManyField(related_name='conferences', to='news_final.category'),
        ),
    ]
