# Generated by Django 4.1.7 on 2023-03-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_final', '0003_alter_conference_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='category',
            new_name='categories',
        ),
    ]
