# Generated by Django 4.1.7 on 2023-03-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('income', models.CharField(max_length=100)),
                ('opportunity_to_work_from_home', models.CharField(max_length=50)),
                ('timetable', models.CharField(max_length=100)),
                ('additional_requirements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('short_summary', models.TextField()),
                ('work_in_the_office', models.CharField(max_length=50)),
                ('online_work', models.CharField(max_length=50)),
                ('individual_feature', models.TextField()),
                ('working_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.vacancies')),
            ],
        ),
    ]
